Add version to the binary during build
arduino/imgtool-packing pull request #12
Opened 2022-05-12 15:08 UTC by umbynos

Replace the string in the patch overriding the version, This way when running `imgtool version` the correct version is reported.

2022-05-12 15:10 UTC, umbynos commented
Example of the problem can be seen here https://github.com/arduino/imgtool-packing/pull/11#issuecomment-1125061411

2022-05-13 06:51 UTC, per1234 reviewed
What do you think about using an obvious placeholder in the patch to make the system more clear?

Like changing the current patch:

https://github.com/arduino/imgtool-packing/blob/5619cae603dfcef2870e66f510135b032979a828/patches/0008-Imgtool-Append-arduino-to-version-string.patch#L18-L19

To something like this:

```patch
-imgtool_version = "1.8.0"
+imgtool_version = "ARDUINO_VERSION_PLACEHOLDER"
```

2022-05-13 07:17 UTC, per1234 approved these changes

2022-05-13 07:18 UTC, per1234 requested changes
I forgot I was going to make one follow-up suggestion if the placeholder idea was accepted:

Update the patch message to reflect the new nature of the patch:

https://github.com/arduino/imgtool-packing/blob/2fd18071dbab7179fc95f2d23a646a8bf91a55c2/patches/0008-Imgtool-Append-arduino-to-version-string.patch#L4

2022-05-13 09:10 UTC, umbynos commented
Test release here https://github.com/arduino/imgtool-packing/releases/tag/1.8.0-rc7

2022-05-13 09:12 UTC, umbynos commented
```
❰umberto❙~/Downloads/imgtool_1.8.0-rc7_Linux_64bit❱✔≻ ./imgtool version                                                              11:11:49
1.8.0-rc7
```

2022-05-13 11:19 UTC, per1234 requested changes

2022-05-13 11:19 UTC, per1234 commented on .github/workflows/release.yml
> +        run: perl -pi.bak -e "s/ARDUINO_VERSION_PLACEHOLDER/${GITHUB_REF/refs\/tags\//}/g" 0008-Imgtool-Append-arduino-to-version-string.patch
```suggestion
        run: perl -pi -e "s/ARDUINO_VERSION_PLACEHOLDER/${GITHUB_REF/refs\/tags\//}/g" 0008-Imgtool-Append-arduino-to-version-string.patch
```
There is no need to make a backup file that won't be used.

2022-05-13 11:19 UTC, per1234 commented on .github/workflows/release.yml
> +        run: sed -i "s/ARDUINO_VERSION_PLACEHOLDER/${GITHUB_REF/refs\/tags\//}/" 0008-Imgtool-Append-arduino-to-version-string.patch
```suggestion
        run: perl -pi -e "s/ARDUINO_VERSION_PLACEHOLDER/${GITHUB_REF/refs\/tags\//}/g" 0008-Imgtool-Append-arduino-to-version-string.patch
```
Using a consistent placeholder replacement command throughout the workflow will make it easier to understand and maintain.

`sed` and `perl` are confusing enough on their own for dummies like me without having to figure both of them out at the same time!

2022-05-13 15:15 UTC, per1234 approved these changes

2022-05-13 15:38 UTC, merged